services:
  ufc-db:
    image: postgres:17.3
    container_name: ufc-db 
    environment:
      POSTGRES_USER: aboud
      POSTGRES_PASSWORD: ufc123
      POSTGRES_DB: ufcdb
    ports:
      - "5432:5432"
    volumes:
      - ufc_db_data:/var/lib/postgresql/data

  scrapyd:
    build:
      context: .
      dockerfile: Dockerfiles/scrapyd.Dockerfile
    container_name: scrapyd
    ports:
      - "6800:6800"
    volumes:
      - scrapyd_data:/var/lib/scrapyd
      - ./scrapyd.conf:/etc/scrapyd/scrapyd.conf
    

volumes:
  ufc_db_data:
  scrapyd_data:
