services:
  ufc-db:
    image: postgres:17.3
    container_name: ufc-db 
    environment:
      POSTGRES_USER: aboud
      POSTGRES_PASSWORD: ufc123
      POSTGRES_DB: ufcdb
    ports:
      - "5432:5432"
    volumes:
      - ufc_db_data:/var/lib/postgresql/data
    
  scrapy:
    build:
      context: .
      dockerfile: Dockerfiles/scrapy.Dockerfile
    depends_on:
      - ufc-db
    volumes:
      - .:/app
  
  
volumes:
  ufc_db_data:
